# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(blank=True, upload_to='images/')),
                ('weight', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('goal', models.CharField(choices=[('Losing weight', 'Losing weight'), ('Getting toned', 'Getting toned'), ('Getting bigger', 'Getting bigger'), ('Maintain fitness', 'Maintain fitness')], max_length=30)),
                ('contact', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
