# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='working_hours',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
