# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_gym_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='working_hours',
            field=models.TextField(),
        ),
    ]
